version: '3.3'

services:
  stage-db:
    container_name: mdb
    image: mariadb
    restart: always
    ports:
      - "3310:3306"
    env_file: 
      - ./db/.env.stage
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci",
    ]
    volumes:
      - ./stage/db/db-data:/var/lib/mysql
      - ./db/mariadb.cnf:/etc/mysql/mariadb.cnf
       # Pointer vers un dossier qui aura des scripts d'initialisation de notre base
      - ./db/stage-initdb.d:/docker-entrypoint-initdb.d
      # Ajouter le DDL qui va tourner en dernier
      #- ./db/ddl/ddl.sql:/docker-entrypoint-initdb.d/999-ddl.sql
    networks:
      - api-stage-network
   

  stage-api:
    build: 
      context: ./
      dockerfile: ./Dockerfile.prod
    container_name: api
    ports:
      - "5060:5050"
    environment:
      - NODE_ENV=prod
      - PORT=5050
      - DB_HOST=stage-db
      - DB_USER=api-stage
      - DB_PASSWORD=api-stage-password
      - DB_DATABASE=challenge_stage
      - SECRET_API_KEY=f9be90ca4421737740209b43f8468d8b
      - PUBLIC_API_KEY=4314ac36374fdfb88a963913c5f472d4
      - SENDER_EMAIL=louis.78100@hotmail.fr
      - SENDER_PASSWORD=Zawadka78
      - SENDER_SERVICE=hotmail
      - REDIRECT_LOGIN_URL=http://localhost:5050/auth/loginLink?jwt=
      - ACCESS_TOKEN_SECRET=a9cdc3e9862b38ec880f07c53346b7cae9a3e88c4f2a0b62c83cbbb748771b5c
      - ACCESS_LOGIN_TOKEN=a9cdc3e9862b38ec880f07c53346b7cae9a3e88c4f2a0b62c83cbbb748771b5c
    networks:
      - api-stage-network
    restart: always
    depends_on:
      - stage-db
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "500m"


networks:
  api-stage-network:
    driver: bridge
